### PR TITLE
Fix renew/delete race in DT.AzureStorage

### LINKED ISSUE #1196: Duplicate activity execution due to pop-receipt mismatch
In DurableTask.AzureStorage v2.0.1, there is a race condition where we attempt to renew a message at the same time we delete it. If the renew happens slightly before the delete, it can result in the delete operation failing, and the activity getting run a second time after the visibility timeout expires.

This might be a regression introduced in v2.0.0 when we moved to the new Azure Storage SDK. We had this exact problem in earlier versions of the SDK. However, the retry fix we had for this appears to not work correctly in the newer version.

### PR DESCRIPTION
**Pull request by cgillum**
Fixes #1196 

This issue was discovered as part of investigating ICM#608312432. More details in the issue description. The fix is to retry the delete operation if it fails due to a pop-receipt mismatch. This PR also makes small logging improvements that should help make these kinds of problems easier to diagnose.

I created a console app to reproduce the problem locally and confirm the error details for this kind of scenario.

### CODE REVIEW

File: src/DurableTask.AzureStorage/Storage/Queue.cs [hunk 1]
```diff
@@ -83,6 +83,8 @@ await this.queueClient
                     queueMessage.PopReceipt,
                     cancellationToken)
                 .DecorateFailure();
+
+            this.stats.MessagesUpdated.Increment();
```
Comment (bachuv) [inline src/DurableTask.AzureStorage/Storage/Queue.cs:87]: Is this change part of the logging improvements that were made in this PR?

**Review by nytian — APPROVED** [review]

File: src/DurableTask.AzureStorage/Storage/Queue.cs (hunk 1 above)
Comment (cgillum) [reply src/DurableTask.AzureStorage/Storage/Queue.cs:87]: It's part of it, yes. I want to make sure we're tracking message deletes as part of the counts that we report in our logs.
